### PR TITLE
Update dependencies and various fixes

### LINKED ISSUE #4: `patterns` default option doesn't work
In Metalsmith 1.0 there was an [API change](https://github.com/segmentio/metalsmith/blob/master/History.md#100---september-29-2014) for `source()` so that if no option is given it returns the absolute path to the `src` directory. So, when calling `matchGlobArray` all the files fail to pass the test and `slug()` doesn't do anything. Example input for `matchGlobArray` when using default `patterns` value:

    file:    articles/20150416-ror_ca.md
    pattern: /Users/doup/Code/gra-web-new/src/** (from ms.source())
    ---
    minimatch result:  false

A workaround is to pass the `patterns` option to `slug()`, e.g:

    .use(slug({ patterns: ['*.md'] }))

### PR DESCRIPTION
**Pull request by doup**
Hi, I've made some changes to update it to the latest Metalsmith + dependencies. Summary:

- Update `node-slug` & `minimatch`
- Tests with Metalsmith `1.x`
- Improved test coverage
- Better integration with `node-slug`. `lowercase` option removed in favor of `node-slug`s `lower`. `lowercase` should still work for backward compatibility.
- Fixed `renameFiles` option
- Fixed #4 
- Updated README

Merge, and pump version to `0.7.0`? :smile:

### CODE REVIEW

**Comment by doup** [comment]
ping @nsonnad

**Comment by nsonnad** [comment]
Thanks for your work on this. I'm getting a bunch of `ENOENT` and `ENOTEMPTY` errors on running `npm test`, possibly related to the metalsmith upgrade?

**Comment by doup** [comment]
Sorry it's my fault, I though it was something with my setup… obviously it's not.
I'll check it this afternoon. :scream:

**Comment by doup** [comment]
The issue was with `tap`s `t.plan` which (somehow, I still don't understand how) was making the tests run in parallel conficting the different metalsmith builds.

**Pull request merged**
