### PR TITLE
Adds capability to manually override slug in files (issue #7)

### PR DESCRIPTION
**Pull request by almirfilho**
As we agreed in issue #7. =)

### CODE REVIEW

**Comment by nsonnad** [comment]
Hmm do we think a user would ever want to slugify that override field? Wondering whether we should do
```
var newSlug;
if (currFile.slug) {
  newSlug = slug(currFile.slug, slugOpts);
} else {
  newSlug = slug(currFile[opts.property], slugOpts);
}
```
So that it's just declaring a manual override field? That way if somebody changes their `slugOpts` the slugged property could be kept in sync.

**Comment by almirfilho** [comment]
You're right. It totally makes sense. I'm gonna change it (and add one more test for that).

**Comment by nsonnad** [comment]
Thanks, could you also add a couple lines on this to the README?

**Comment by almirfilho** [comment]
It's done. Please take a look @nsonnad.
Can you close and publish a new version, too?
Thanks!

**Comment by nsonnad** [comment]
Nice work. Published as 0.2.0 for the new feature

**Pull request merged**
